name: CDN Publish

on:
  release:
    types: [prereleased, released]

env:
  WORKFLOW: facebook-storage.yml
  NODE_VERSION: 14
  VUE_PATH: _dev
  BUILD_PATH: views

jobs:
  publish:
    name: CDN publish
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag
        run: echo TAG=$(echo $GITHUB_REF | cut -d / -f 3) >> $GITHUB_OUTPUT

      - name: Trigger storage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ env.WORKFLOW }}
          repo: PrestaShopCorp/services-deployment
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: 'refs/heads/main'
          inputs: '{ "version": "${{ steps.get_tag.outputs.TAG }}", "nodeVersion": "${{ env.NODE_VERSION }}", "vuejsPath": "${{ env.VUE_PATH }}", "vuejsBuildPath": "${{ env.BUILD_PATH }}", "isRelease": "${{ !github.event.release.prerelease && true || false }}" }'
