name: Storybook CI/CD

on:
  pull_request:
    types: [opened,edited,reopened,synchronize,labeled]
  push:
    branches:
      - master

jobs:
  alpha:
    name: Alpha - Storybook
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'Storybook Test')

    steps:
      - name: Get branch name
        id: branch
        uses: tj-actions/branch-names@v5.1

      - name: Trigger build and deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: facebook-storybook.yml
          repo: PrestaShopCorp/services-deployment
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: 'refs/heads/main'
          inputs: '{ "branch": "${{ steps.branch.outputs.current_branch }}", "nodeVersion": "14", "path": "_dev", "issue": "${{ github.event.number }}" }'

  stable:
    name: Stable - Storybook
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Get branch name
        id: branch
        uses: tj-actions/branch-names@v5.1

      - name: Trigger build and deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: facebook-storybook.yml
          repo: PrestaShopCorp/services-deployment
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: 'refs/heads/main'
          inputs: '{ "branch": "${{ steps.branch.outputs.current_branch }}", "nodeVersion": "14", "path": "_dev", "environment": "stable" }'
